src/Entity/Reinscription.php
<?php

namespace App\Entity;

use App\Repository\ReinscriptionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReinscriptionRepository::class)
 */
class Reinscription
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Inscription::class, inversedBy="reinscriptions")
     */
    private $nom_app;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $annee_universitaire;

    /**
     * @ORM\Column(type="date")
     */
    private $date_reinscription;

    /**
     * @ORM\ManyToOne(targetEntity=Groupe::class, inversedBy="reinscriptions")
     */
    private $groupe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomApp(): ?Inscription
    {
        return $this->nom_app;
    }

    public function setNomApp(?Inscription $nom_app): self
    {
        $this->nom_app = $nom_app;

        return $this;
    }

    public function getAnneeUniversitaire(): ?string
    {
        return $this->annee_universitaire;
    }

    public function setAnneeUniversitaire(string $annee_universitaire): self
    {
        $this->annee_universitaire = $annee_universitaire;

        return $this;
    }

    public function getDateReinscription(): ?\DateTimeInterface
    {
        return $this->date_reinscription;
    }

    public function setDateReinscription(\DateTimeInterface $date_reinscription): self
    {
        $this->date_reinscription = $date_reinscription;

        return $this;
    }

    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }
}

src/Form/ReinscriptionType.php
<?php

namespace App\Form;

use App\Entity\Groupe;
use App\Entity\Inscription;
use App\Entity\Reinscription;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ReinscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_app', EntityType::class, [
                'placeholder' => 'Veuillez choisir',
                "attr" => array (
                    "class" => "form-control"
                 ),
                'class' => Inscription::class,
                'query_builder' => function(EntityRepository $apprenant){
                    return $apprenant->createQueryBuilder('a')
                            ->orderBy('a.nom_app', 'ASC');
                }
            ])
            ->add('date_reinscription', DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                "attr" => array (
                    "class" => "form-control",                        
                    'required'   => true,                    
                )
            ])
            ->add('groupe', EntityType::class, [
                'placeholder' => 'Veuillez choisir',
                "attr" => array (
                    "class" => "form-control"
                 ),
                'class' => Groupe::class,
                'query_builder' => function(EntityRepository $groupe){
                    return $groupe->createQueryBuilder('g')
                            ->orderBy('g.nomGroupe', 'ASC');
                }
            ])
            ->add('annee_universitaire', TextType::class, [
                "attr" => array (
                    "class" => "form-control",
                    'required'   => true,
                )
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reinscription::class,
        ]);
    }
}

src/Controller/ReinscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Reinscription;
use App\Form\ReinscriptionType;
use App\Repository\MenuUserRepository;
use App\Repository\MenuVisiteurRepository;
use App\Repository\MenuApprenantRepository;
use App\Repository\MenuFormateurRepository;
use App\Repository\ReinscriptionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MenuAdministrateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/reinscription")
 */
class ReinscriptionController extends AbstractController
{
    /**
     * @Route("/", name="reinscription_index", methods={"GET"})
     */
    public function index(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,ReinscriptionRepository $reinscriptionRepository): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
       
        return $this->render('reinscription/index.html.twig', [
            'reinscriptions' => $reinscriptionRepository->findAll(),
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/new", name="reinscription_new", methods={"GET","POST"})
     */
    public function new(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request): Response
    {
        $reinscription = new Reinscription();
        $form = $this->createForm(ReinscriptionType::class, $reinscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reinscription);
            $entityManager->flush();
            $this->addFlash(
                'msg','Enregistrer avec succès'
            );

            return $this->redirectToRoute('reinscription_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('reinscription/new.html.twig', [
            'reinscription' => $reinscription,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="reinscription_show", methods={"GET"})
     */
    public function show(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Reinscription $reinscription): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('reinscription/show.html.twig', [
            'reinscription' => $reinscription,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reinscription_edit", methods={"GET","POST"})
     */
    public function edit(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request, Reinscription $reinscription): Response
    {
        $form = $this->createForm(ReinscriptionType::class, $reinscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash(
                'msg','Modification réussit!'
            );

            return $this->redirectToRoute('reinscription_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('reinscription/edit.html.twig', [
            'reinscription' => $reinscription,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="reinscription_delete", methods={"POST"})
     */
    public function delete(Request $request, Reinscription $reinscription): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reinscription->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reinscription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reinscription_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reinscription/_delete_form.html.twig
<form method="post" action="{{ path('reinscription_delete', {'id': reinscription.id}) }}" onsubmit="return confirm('Etes-vous sur de supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reinscription.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/reinscription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification reinscription{% endblock %}

{% block body %}
	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('reinscription_index') }}" class="btn btn-sm btn-neutral">Aller à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="col-xl-12 order-xl-1">
				<div class="card">
					{{ form_start(form) }}
					<div class="card-header">
						<div class="row align-items-center">
							<div class="col-8">
								<h3 class="mb-0">Modification reinscription
								</h3>
							</div>
							<div class="col-4 text-right">
								<button class="btn btn-sm btn-primary">Modifier</button>
							</div>
						</div>
					</div>
					<div class="card-body">
						<h6 class="heading-small text-muted mb-4">Information génerale</h6>
						<div class="pl-lg-4">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Apprenant</label>
										{{ form_widget(form.nom_app) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Date de reinscription</label>
										{{ form_widget(form.date_reinscription) }}
									</div>
								</div>
							</div>
							<div class="row">
                            <div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Groupe</label>
										{{ form_widget(form.groupe) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Année universitaire</label>
										{{ form_widget(form.annee_universitaire) }}
									</div>
								</div>
							</div>
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
			{{include ("include/footer.html.twig")}}
		{% endblock %}

templates/reinscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des reinscriptions{% endblock %}
{% set active = 'reinscription'%}
{% block body %}
	{{include ("include/menu.html.twig")}}
    
	<div class="main-content" id="panel">

		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('reinscription_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							{# <a href="#" class="btn btn-sm btn-neutral">Filtre</a> #}
						</div>
					</div>
					<div class="row align-items-center py-4">
						<div class="col-lg-9 col-8"></div>
						<div class="col-lg-3 col-4 text-right">
						{% for message in app.flashes('msg') %}
							<div class="alert alert-success alert-dismissible fade show" role="alert">
								<strong>{{message}}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col">
					<div
						class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-7">
									<h3 class="mb-0">Liste des apprenants reinscrit
									</h3>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table class="table table-flush" id="datatable-search">
								<thead class="thead-light">
									<tr>
										<th scope="col">Apprenants</th>
										<th scope="col">Année universitaire</th>
										<th scope="col">Groupe</th>
										<th scope="col">Date de reinscription</th>
										<th scope="col" class="text-right">Actions</th>
									</tr>
								</thead>
								<tbody class="list">
									{% for reinscription in reinscriptions %}
										<tr>
                                            <td>{{ reinscription.nomApp }}</td>										
                                            <td>{{ reinscription.anneeUniversitaire }}</td>
											<td>{{ reinscription.groupe }}</td>
                                            <td>{{ reinscription.dateReinscription ? reinscription.dateReinscription|date('Y-m-d') : '' }}</td>
											<td class="text-right">
												<div class="dropdown">
													<a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
														<i class="fas fa-ellipsis-v"></i>
													</a>
													<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
														<a class="dropdown-item" href="{{ path('reinscription_show', {'id': reinscription.id}) }}">Détail</a>
														<a class="dropdown-item" href="{{ path('reinscription_edit', {'id': reinscription.id}) }}">Modifier</a>
													</div>
												</div>
											</td>
										</tr>
									{% else %}
										<tr>
											<td colspan="5">Aucun enregistrement </td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
						<div class="card-footer py-4">
							<nav aria-label="...">
								<ul class="pagination justify-content-end mb-0">
									<li class="page-item disabled">
										<a class="page-link" href="#" tabindex="-1">
											<i class="fas fa-angle-left"></i>
											<span class="sr-only">Previous</span>
										</a>
									</li>
									<li class="page-item active">
										<a class="page-link" href="#">1</a>
									</li>
									<li class="page-item">
										<a class="page-link" href="#">2
											<span class="sr-only">(current)</span>
										</a>
									</li>
									<li class="page-item">
										<a class="page-link" href="#">3</a>
									</li>
									<li class="page-item">
										<a class="page-link" href="#">
											<i class="fas fa-angle-right"></i>
											<span class="sr-only">Next</span>
										</a>
									</li>
								</ul>
							</nav>
						</div>
					</div>
				</div>
			</div>

			{{include ("include/footer.html.twig")}}

		{% endblock %}

templates/reinscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau reinscription{% endblock %}

{% block body %}
	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('reinscription_index') }}" class="btn btn-sm btn-neutral">Aller à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="col-xl-12 order-xl-1">
				<div class="card">
					{{ form_start(form) }}
					<div class="card-header">
						<div class="row align-items-center">
							<div class="col-8">
								<h3 class="mb-0">Nouveau reinscription
								</h3>
							</div>
							<div class="col-4 text-right">
								<button class="btn btn-sm btn-primary">Ajouter</button>
							</div>
						</div>
					</div>
					<div class="card-body">
						<h6 class="heading-small text-muted mb-4">Information génerale</h6>
						<div class="pl-lg-4">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Apprenant</label>
										{{ form_widget(form.nom_app) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Date de reinscription</label>
										{{ form_widget(form.date_reinscription) }}
									</div>
								</div>
							</div>
							<div class="row">
                            <div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Groupe</label>
										{{ form_widget(form.groupe) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Année universitaire</label>
										{{ form_widget(form.annee_universitaire) }}
									</div>
								</div>
							</div>
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
			{{include ("include/footer.html.twig")}}
		{% endblock %}

templates/reinscription/show.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Reinscription
{% endblock %}

{% block body %}
	<h1>Reinscription</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ reinscription.id }}</td>
			</tr>
			<tr>
				<th>Annee_universitaire</th>
				<td>{{ reinscription.anneeUniversitaire }}</td>
			</tr>
			<tr>
				<th>Date_reinscription</th>
				<td>{{ reinscription.dateReinscription ? reinscription.dateReinscription|date('Y-m-d') : '' }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('reinscription_index') }}">back to list</a>

	<a href="{{ path('reinscription_edit', {'id': reinscription.id}) }}">edit</a>

	{{ include('reinscription/_delete_form.html.twig') }}
{% endblock %} #}

{% extends 'base.html.twig' %}

{% block title %}Détail du reinscription
{% endblock %}

{% block body %}

	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('reinscription_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							<a href="{{ path('reinscription_index') }}" class="btn btn-sm btn-neutral">Retour à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col-xl order-xl-1">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-8">
									<h3 class="mb-0">Détail de reinscription
									</h3>
								</div>
								<div class="col-4 text-right">
									{{ include('reinscription/_delete_form.html.twig') }}
								</div>
							</div>
						</div>
						<div class="card-body">
							<div class="pl-lg-4">
								<table class="table">
									<tbody>
										<tr>
											<th>Apprenant</th>
											<td>{{ reinscription.nomApp }}</td>
										</tr>
										<tr>
											<th>Groupe</th>
											<td>{{ reinscription.groupe  }}</td>
										</tr>
										<tr>
											<th>Annee_universitaire</th>
											<td>{{ reinscription.anneeUniversitaire }}</td>
										</tr>
										<tr>
											<th>Date_reinscription</th>
											<td>{{ reinscription.dateReinscription ? reinscription.dateReinscription|date('Y-m-d') : '' }}</td>
										</tr>

									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{{include ("include/footer.html.twig")}}

{% endblock %}