src/Entity/Apprenant.php
<?php

namespace App\Entity;

use App\Repository\ApprenantRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ApprenantRepository::class)
 */
class Apprenant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Inscription::class, inversedBy="apprenants")
     */
    private $nom_app;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_app;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $photo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomApp(): ?Inscription
    {
        return $this->nom_app;
    }

    public function setNomApp(?Inscription $nom_app): self
    {
        $this->nom_app = $nom_app;

        return $this;
    }

    public function getNumeroApp(): ?int
    {
        return $this->numero_app;
    }

    public function setNumeroApp(int $numero_app): self
    {
        $this->numero_app = $numero_app;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Form/ApprenantType.php
<?php

namespace App\Form;

use App\Entity\Apprenant;
use App\Entity\Inscription;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ApprenantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder            
            ->add('nom_app', EntityType::class, [
                'placeholder' => 'Veuillez choisir',
                "attr" => array (
                    "class" => "form-control"
                 ),
                'class' => Inscription::class,
                'query_builder' => function(EntityRepository $apprenant){
                    return $apprenant->createQueryBuilder('a')
                            ->orderBy('a.nom_app', 'ASC');
                }
            ])
            ->add('numero_app', TextType::class, [
                "attr" => array (
                    "class" => "form-control",
                    'required'   => true,
                )
            ])
            ->add('photo', FileType::class, 
                array(
                    'data_class' => null,
                    'required'   => false,
                )
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Apprenant::class,
        ]);
    }
}

src/Controller/ApprenantController.php
<?php

namespace App\Controller;

use App\Entity\Apprenant;
use App\Form\ApprenantType;
use App\Repository\MenuUserRepository;
use App\Repository\ApprenantRepository;
use App\Repository\MenuVisiteurRepository;
use App\Repository\MenuApprenantRepository;
use App\Repository\MenuFormateurRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MenuAdministrateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/apprenant")
 */
class ApprenantController extends AbstractController
{
    /**
     * @Route("/", name="apprenant_index", methods={"GET"})
     */
    public function index(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,ApprenantRepository $apprenantRepository): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('apprenant/index.html.twig', [
            'apprenants' => $apprenantRepository->findAll(),
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/new", name="apprenant_new", methods={"GET","POST"})
     */
    public function new(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request): Response
    {
        $apprenant = new Apprenant();
        $form = $this->createForm(ApprenantType::class, $apprenant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //File upload
            $file = $apprenant->getPhoto();
            $filename = uniqid().'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('images_directory'),
                $filename
            );            
            //Insert data
            $entityManager = $this->getDoctrine()->getManager();
            $apprenant->setPhoto($filename);
            $entityManager->persist($apprenant);
            $entityManager->flush();
            //Alert 
            $this->addFlash(
                'msg','Enregistrer avec succès'
            );

            return $this->redirectToRoute('apprenant_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('apprenant/new.html.twig', [
            'apprenant' => $apprenant,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="apprenant_show", methods={"GET"})
     */
    public function show(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Apprenant $apprenant): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('apprenant/show.html.twig', [
            'apprenant' => $apprenant,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="apprenant_edit", methods={"GET","POST"})
     */
    public function edit(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request, Apprenant $apprenant): Response
    {
        $form = $this->createForm(ApprenantType::class, $apprenant);
        $form->handleRequest($request);
        $photo = $form->get('photo')->getData();
        dump($photo);

        if ($form->isSubmitted() && $form->isValid()) {
            //nouvelle image envoyée depuis le form
             if ( $apprenant->getPhoto() !=null ){
                $file = $apprenant->getPhoto();
                $filename = uniqid().'.'.$file->guessExtension();
                $file->move(
                    $this->getParameter('images_directory'),
                    $filename
                );
                $apprenant->setPhoto($filename);
             }else{ // aucune nouvelle image envoyée
                //on recupère l'ancienne image
                $apprenant->setPhoto($apprenant->getPhoto());
             }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($apprenant);
            $entityManager->flush();
            $this->addFlash(
                'msg','Modification réussit!'
            );

            return $this->redirectToRoute('apprenant_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('apprenant/edit.html.twig', [
            'apprenant' => $apprenant,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
            'photo' => $photo
        ]);
    }

    /**
     * @Route("/{id}", name="apprenant_delete", methods={"POST"})
     */
    public function delete(Request $request, Apprenant $apprenant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$apprenant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($apprenant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('apprenant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/apprenant/_delete_form.html.twig
<form method="post" action="{{ path('apprenant_delete', {'id': apprenant.id}) }}" onsubmit="return confirm('Etes-vous sur de supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ apprenant.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/apprenant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification apprenant{% endblock %}

{% block body %}
	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('apprenant_index') }}" class="btn btn-sm btn-neutral">Aller à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="col-xl-12 order-xl-1">
				<div class="card">
					{{ form_start(form) }}
					<div class="card-header">
						<div class="row align-items-center">
							<div class="col-8">
								<h3 class="mb-0">Modification apprenant
								</h3>
							</div>
							<div class="col-4 text-right">
								<button class="btn btn-sm btn-primary">Modifier</button>
							</div>
						</div>
					</div>
					<div class="card-body">
						<h6 class="heading-small text-muted mb-4">Information génerale</h6>
						<div class="pl-lg-4">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Nom apprenant</label>
										{{ form_widget(form.nom_app) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Numero apprenant</label>
										{{ form_widget(form.numero_app) }}
									</div>
								</div>
							</div>
                            <div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Photo</label>
										{{ form_widget(form.photo,{'attr' :{'required' : false, 'value': asset('uploads/images/' ~photo ) }}) }}
									</div>
								</div>
							</div>                            
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
			{{include ("include/footer.html.twig")}}
		{% endblock %}

templates/apprenant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des apprenants
{% endblock %}
{% set active = 'apprenant'%}

{% block body %}

	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('apprenant_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							{# <a href="#" class="btn btn-sm btn-neutral">Filtre</a> #}
						</div>
					</div>
					<div class="row align-items-center py-4">
						<div class="col-lg-9 col-8"></div>
						<div class="col-lg-3 col-4 text-right">
						{% for message in app.flashes('msg') %}
							<div class="alert alert-success alert-dismissible fade show" role="alert">
								<strong>{{message}}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-7">
									<h3 class="mb-0">Liste des apprenants
									</h3>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table id="datatable-search">
								<thead>
									<tr>
										<th scope="col"><strong>Photo</strong></th>
										<th scope="col"><strong>Numero</strong></th>
										<th scope="col"><strong>Nom apprenant</strong></th>
										<th scope="col"><strong>Actions</strong></th>
									</tr>
								</thead>
								<tbody class="list">
									{% for apprenant in apprenants %}
										<tr>
											<td>
												<div class="avatar-group">
													<a href="#" class="avatar rounded-circle mr-3" data-toggle="tooltip" data-original-title="{{apprenant.nomApp}}">
														<img alt="Image placeholder" src="{{ asset('uploads/images/' ~apprenant.photo)}}">
													</a>
												</div>
											</td>
											<td>{{apprenant.numeroApp}}</td>
											<th scope="row">
												<div class="media align-items-center">
													<div class="media-body">
														<span class="name mb-0 text-sm">{{apprenant.nomApp}}</span>
													</div>
												</div>
											</th>

											<td>
												<div class="dropdown">
													<a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
														<i class="fas fa-ellipsis-v"></i>
													</a>
													<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
														<a class="dropdown-item" href="{{ path('apprenant_show', {'id': apprenant.id}) }}">Détail</a>
														<a class="dropdown-item" href="{{ path('apprenant_edit', {'id': apprenant.id}) }}">Modifier</a>
													</div>
												</div>
											</td>
										</tr>
									{% else %}
										<tr>
											<td colspan="4">no records found</td>
										</tr>
									{% endfor %}
								</tbody>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>


	{{include ("include/footer.html.twig")}}

{% endblock %}

templates/apprenant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau apprenant{% endblock %}

{% block body %}
	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('apprenant_index') }}" class="btn btn-sm btn-neutral">Aller à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="col-xl-12 order-xl-1">
				<div class="card">
					{{ form_start(form) }}
					<div class="card-header">
						<div class="row align-items-center">
							<div class="col-8">
								<h3 class="mb-0">Nouveau apprenant
								</h3>
							</div>
							<div class="col-4 text-right">
								<button class="btn btn-sm btn-primary">Ajouter</button>
							</div>
						</div>
					</div>
					<div class="card-body">
						<h6 class="heading-small text-muted mb-4">Information génerale</h6>
						<div class="pl-lg-4">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Nom apprenant</label>
										{{ form_widget(form.nom_app) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Numero apprenant</label>
										{{ form_widget(form.numero_app) }}
									</div>
								</div>
							</div>
                            <div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Photo</label>
										{{ form_widget(form.photo) }}
									</div>
								</div>
							</div>                            
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
			{{include ("include/footer.html.twig")}}
		{% endblock %}

templates/apprenant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du apprenant
{% endblock %}

{% block body %}

	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('apprenant_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							<a href="{{ path('apprenant_index') }}" class="btn btn-sm btn-neutral">Retour à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col-xl order-xl-1">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-8">
									<h3 class="mb-0">Détail apprenant
									</h3>
								</div>
								<div class="col-4 text-right">
									{{ include('apprenant/_delete_form.html.twig') }}
								</div>
							</div>
						</div>
						<div class="card-body">
							<div class="pl-lg-4">
								<table class="table">
									<tbody>
										<tr>
											<th>Photo</th>
											<td><img alt="Image placeholder" src="{{ asset('uploads/images/' ~apprenant.photo)}}"></td>
										</tr>
										<tr>
											<th>Numero</th>
											<td>{{ apprenant.numeroApp }}</td>
										</tr>
										<tr>
											<th>Nom apprenant</th>
											<td>{{ apprenant.nomApp }}</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{{include ("include/footer.html.twig")}}

{% endblock %}