src/Entity/Inscription.php
<?php

namespace App\Entity;

use App\Repository\InscriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InscriptionRepository::class)
 */
class Inscription
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom_pere;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $fonction_pere;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $prenom_pere;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom_mere;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $prenom_mere;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $fonction_mere;

    /**
     * @ORM\Column(type="integer")
     */
    private $immatricule_app;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom_app;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $prenom_app;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance_app;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $sexe_app;

    /**
     * @ORM\Column(type="text")
     */
    private $adresse_app;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $email_app;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $telephone_app;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $etablissement;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $categorie;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $annee_universitaire;

    /**
     * @ORM\ManyToOne(targetEntity=Groupe::class, inversedBy="inscriptions")
     */
    private $groupe;

    /**
     * @ORM\OneToMany(targetEntity=Reinscription::class, mappedBy="nom_app")
     */
    private $reinscriptions;

    /**
     * @ORM\OneToMany(targetEntity=Apprenant::class, mappedBy="nom_app")
     */
    private $apprenants;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="nom_app")
     */
    private $notes;

    /**
     * @ORM\OneToMany(targetEntity=Assiduite::class, mappedBy="apprenant")
     */
    private $assiduite_app;

    /**
     * @ORM\Column(type="date")
     */
    private $date_inscription;

    public function __construct()
    {
        $this->reinscriptions = new ArrayCollection();
        $this->apprenants = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->assiduite_app = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->nom_app;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPere(): ?string
    {
        return $this->nom_pere;
    }

    public function setNomPere(string $nom_pere): self
    {
        $this->nom_pere = $nom_pere;

        return $this;
    }

    public function getFonctionPere(): ?string
    {
        return $this->fonction_pere;
    }

    public function setFonctionPere(string $fonction_pere): self
    {
        $this->fonction_pere = $fonction_pere;

        return $this;
    }

    public function getPrenomPere(): ?string
    {
        return $this->prenom_pere;
    }

    public function setPrenomPere(string $prenom_pere): self
    {
        $this->prenom_pere = $prenom_pere;

        return $this;
    }

    public function getNomMere(): ?string
    {
        return $this->nom_mere;
    }

    public function setNomMere(string $nom_mere): self
    {
        $this->nom_mere = $nom_mere;

        return $this;
    }

    public function getPrenomMere(): ?string
    {
        return $this->prenom_mere;
    }

    public function setPrenomMere(string $prenom_mere): self
    {
        $this->prenom_mere = $prenom_mere;

        return $this;
    }

    public function getFonctionMere(): ?string
    {
        return $this->fonction_mere;
    }

    public function setFonctionMere(string $fonction_mere): self
    {
        $this->fonction_mere = $fonction_mere;

        return $this;
    }

    public function getImmatriculeApp(): ?int
    {
        return $this->immatricule_app;
    }

    public function setImmatriculeApp(int $immatricule_app): self
    {
        $this->immatricule_app = $immatricule_app;

        return $this;
    }

    public function getNomApp(): ?string
    {
        return $this->nom_app;
    }

    public function setNomApp(string $nom_app): self
    {
        $this->nom_app = $nom_app;

        return $this;
    }

    public function getPrenomApp(): ?string
    {
        return $this->prenom_app;
    }

    public function setPrenomApp(string $prenom_app): self
    {
        $this->prenom_app = $prenom_app;

        return $this;
    }

    public function getDateNaissanceApp(): ?\DateTimeInterface
    {
        return $this->date_naissance_app;
    }

    public function setDateNaissanceApp(\DateTimeInterface $date_naissance_app): self
    {
        $this->date_naissance_app = $date_naissance_app;

        return $this;
    }

    public function getSexeApp(): ?string
    {
        return $this->sexe_app;
    }

    public function setSexeApp(string $sexe_app): self
    {
        $this->sexe_app = $sexe_app;

        return $this;
    }

    public function getAdresseApp(): ?string
    {
        return $this->adresse_app;
    }

    public function setAdresseApp(string $adresse_app): self
    {
        $this->adresse_app = $adresse_app;

        return $this;
    }

    public function getEmailApp(): ?string
    {
        return $this->email_app;
    }

    public function setEmailApp(string $email_app): self
    {
        $this->email_app = $email_app;

        return $this;
    }

    public function getTelephoneApp(): ?string
    {
        return $this->telephone_app;
    }

    public function setTelephoneApp(string $telephone_app): self
    {
        $this->telephone_app = $telephone_app;

        return $this;
    }

    public function getEtablissement(): ?string
    {
        return $this->etablissement;
    }

    public function setEtablissement(string $etablissement): self
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getAnneeUniversitaire(): ?string
    {
        return $this->annee_universitaire;
    }

    public function setAnneeUniversitaire(string $annee_universitaire): self
    {
        $this->annee_universitaire = $annee_universitaire;

        return $this;
    }

    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return Collection|Reinscription[]
     */
    public function getReinscriptions(): Collection
    {
        return $this->reinscriptions;
    }

    public function addReinscription(Reinscription $reinscription): self
    {
        if (!$this->reinscriptions->contains($reinscription)) {
            $this->reinscriptions[] = $reinscription;
            $reinscription->setNomApp($this);
        }

        return $this;
    }

    public function removeReinscription(Reinscription $reinscription): self
    {
        if ($this->reinscriptions->removeElement($reinscription)) {
            // set the owning side to null (unless already changed)
            if ($reinscription->getNomApp() === $this) {
                $reinscription->setNomApp(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Apprenant[]
     */
    public function getApprenants(): Collection
    {
        return $this->apprenants;
    }

    public function addApprenant(Apprenant $apprenant): self
    {
        if (!$this->apprenants->contains($apprenant)) {
            $this->apprenants[] = $apprenant;
            $apprenant->setNomApp($this);
        }

        return $this;
    }

    public function removeApprenant(Apprenant $apprenant): self
    {
        if ($this->apprenants->removeElement($apprenant)) {
            // set the owning side to null (unless already changed)
            if ($apprenant->getNomApp() === $this) {
                $apprenant->setNomApp(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setNomApp($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getNomApp() === $this) {
                $note->setNomApp(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Assiduite[]
     */
    public function getAssiduiteApp(): Collection
    {
        return $this->assiduite_app;
    }

    public function addAssiduiteApp(Assiduite $assiduiteApp): self
    {
        if (!$this->assiduite_app->contains($assiduiteApp)) {
            $this->assiduite_app[] = $assiduiteApp;
            $assiduiteApp->setApprenant($this);
        }

        return $this;
    }

    public function removeAssiduiteApp(Assiduite $assiduiteApp): self
    {
        if ($this->assiduite_app->removeElement($assiduiteApp)) {

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Inscription;
use App\Form\InscriptionType;
use App\Repository\MenuUserRepository;
use App\Repository\InscriptionRepository;
use App\Repository\MenuVisiteurRepository;
use App\Repository\MenuApprenantRepository;
use App\Repository\MenuFormateurRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MenuAdministrateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/inscription")
 */
class InscriptionController extends AbstractController
{
    /**
     * @Route("/", name="inscription_index", methods={"GET"})
     */
    public function index(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,InscriptionRepository $inscriptionRepository): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('inscription/index.html.twig', [
            'inscriptions' => $inscriptionRepository->findAll(),
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/new", name="inscription_new", methods={"GET","POST"})
     */
    public function new(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request): Response
    {
        $inscription = new Inscription();
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($inscription);
            $entityManager->flush();
            $this->addFlash(
                'msg','Enregistrer avec succès!'
            );

            return $this->redirectToRoute('inscription_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('inscription/new.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="inscription_show", methods={"GET"})
     */
    public function show(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Inscription $inscription): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('inscription/show.html.twig', [
            'inscription' => $inscription,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="inscription_edit", methods={"GET","POST"})
     */
    public function edit(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request, Inscription $inscription): Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash(
                'msg','Modification réussit!'
            );

            return $this->redirectToRoute('inscription_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('inscription/edit.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="inscription_delete", methods={"POST"})
     */
    public function delete(Request $request, Inscription $inscription): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inscription->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($inscription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('inscription_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inscription/_delete_form.html.twig
<form method="post" action="{{ path('inscription_delete', {'id': inscription.id}) }}" onsubmit="return confirm('Etes-vous sur de supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inscription.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des apprenants inscrit{% endblock %}
{% set active = 'inscription'%}
{% block body %}

	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('inscription_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							{# <a href="#" class="btn btn-sm btn-neutral">Filtre</a> #}
						</div>
					</div>
				</div>
				<div class="row align-items-center py-4">
					<div class="col-lg-9 col-8"></div>
					<div class="col-lg-3 col-4 text-right">
					{% for message in app.flashes('msg') %}
						<div class="alert alert-success alert-dismissible fade show" role="alert">
							<strong>{{message}}</strong>
							<button type="button" class="close" data-dismiss="alert" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
					{% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-7">
									<h3 class="mb-0">Liste des apprenants inscrit
									</h3>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table id="datatable-search">
								<thead>
									<tr>
                                        <th scope="col"><strong>Immatricule</strong></th>
										<th scope="col"><strong>Nom</strong></th>
										<th scope="col"><strong>Prenom</strong></th>
                                        <th scope="col"><strong>Date de naissance</strong></th>
										<th scope="col"><strong>Sexe</strong></th>
                                        <th scope="col"><strong>Adresse</strong></th>
										<th scope="col"><strong>Email</strong></th>
										<th scope="col"><strong>Télephone</strong></th>
										<th scope="col"><strong>Groupe</strong></th>
										<th scope="col"><strong>Actions</strong></th>
									</tr>
								</thead>
								<tbody class="list">
									{% for inscription in inscriptions %}
										<tr>
                                            <td>{{inscription.immatriculeApp}}</td>
											<th scope="row">
												<div class="media align-items-center">
													<div class="media-body">
														<span class="name mb-0 text-sm">{{ inscription.nomApp }}</span>
													</div>
												</div>
											</th>
                                            <th scope="row">
												<div class="media align-items-center">
													<div class="media-body">
														<span class="name mb-0 text-sm">{{ inscription.prenomApp }}</span>
													</div>
												</div>
											</th>
											<td>{{inscription.dateNaissanceApp ? inscription.dateNaissanceApp|date('Y-m-d') : '' }}</td>
											<td>{{inscription.sexeApp}}</td>
											<td>{{inscription.adresseApp}}</td>
											<td>{{inscription.emailApp}}</td>
											<td>{{inscription.telephoneApp}}</td>
                                            <td>{{inscription.groupe}}</td>										
											<td>
												<div class="dropdown">
													<a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
														<i class="fas fa-ellipsis-v"></i>
													</a>
													<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
														<a class="dropdown-item" href="{{ path('inscription_show', {'id': inscription.id}) }}">Détail</a>
														<a class="dropdown-item" href="{{ path('inscription_edit', {'id': inscription.id}) }}">Modifier</a>
													</div>
												</div>
											</td>
										</tr>
                                        {% else %}
                                        <tr>
                                            <td colspan="10">Aucun enregistrement</td>
                                        </tr>
									{% endfor %}
								</tbody>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="card-footer py-4">
					<nav aria-label="...">
						<ul class="pagination justify-content-end mb-0">
							<li class="page-item disabled">
								<a class="page-link" href="#" tabindex="-1">
									<i class="fas fa-angle-left"></i>
									<span class="sr-only">Previous</span>
								</a>
							</li>
							<li class="page-item active">
								<a class="page-link" href="#">1</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">2
									<span class="sr-only">(current)</span>
								</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">3</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">
									<i class="fas fa-angle-right"></i>
									<span class="sr-only">Next</span>
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>

	{{include ("include/footer.html.twig")}}

{% endblock %}

templates/inscription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail des inscriptions
{% endblock %}

{% block body %}

	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('inscription_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							<a href="{{ path('inscription_index') }}" class="btn btn-sm btn-neutral">Retour à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col-xl-6 order-xl-1">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-8">
									<h3 class="mb-0">Détail de l'inscription
									</h3>
								</div>
                                <div class="col-4 text-right">
                                    {{ include('inscription/_delete_form.html.twig') }}
                                </div>
							</div>
						</div>
						<div class="card-body">
							<div class="pl-lg-4">
								<table class="table">
									<tbody>
										<tr>
											<th>Immatricule</th>
											<td>{{ inscription.immatriculeApp }}</td>
										</tr>
										<tr>
											<th>Nom</th>
											<td>{{ inscription.nomApp }}</td>
										</tr>
										<tr>
											<th>Prenom</th>
											<td>{{ inscription.prenomApp }}</td>
										</tr>
										<tr>
											<th>Date_naissance</th>
											<td>{{ inscription.dateNaissanceApp ? inscription.dateNaissanceApp|date('Y-m-d') : '' }}</td>
										</tr>
										<tr>
											<th>Sexe</th>
											<td>{{ inscription.sexeApp }}</td>
										</tr>
										<tr>
											<th>Adresse</th>
											<td>{{ inscription.adresseApp }}</td>
										</tr>
										<tr>
											<th>Email</th>
											<td>{{ inscription.emailApp }}</td>
										</tr>
										<tr>
											<th>Telephone</th>
											<td>{{ inscription.telephoneApp }}</td>
										</tr>
										<tr>
											<th>Etablissement</th>
											<td>{{ inscription.etablissement }}</td>
										</tr>
										<tr>
											<th>Categorie</th>
											<td>{{ inscription.categorie }}</td>
										</tr>
										<tr>
											<th>Annee_universitaire</th>
											<td>{{ inscription.anneeUniversitaire }}</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-6 order-xl-1">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-8">
									<h3 class="mb-0">Information parentale
									</h3>
								</div>
							</div>
						</div>
						<div class="card-body">
							<div class="pl-lg-4">
								<table class="table">
									<tbody>
										<tr>
											<th>Nom du pere</th>
											<td>{{ inscription.nomPere }}</td>
										</tr>
										<tr>
											<th>Prenom du pere</th>
											<td>{{ inscription.prenomPere }}</td>
										</tr>
										<tr>
											<th>Fonction
											</th>
											<td>{{ inscription.fonctionPere }}</td>
										</tr>
										<tr>
											<th>Nom de la mère</th>
											<td>{{ inscription.nomMere }}</td>
										</tr>
										<tr>
											<th>Prenom de la mère</th>
											<td>{{ inscription.prenomMere }}</td>
										</tr>
										<tr>
											<th>Fonction</th>
											<td>{{ inscription.fonctionMere }}</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{{include ("include/footer.html.twig")}}
    
{% endblock %}