src/Entity/Assiduite.php
<?php

namespace App\Entity;

use App\Repository\AssiduiteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AssiduiteRepository::class)
 */
class Assiduite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $heure_cours;

    /**
     * @ORM\ManyToOne(targetEntity=Matiere::class, inversedBy="assiduites")
     */
    private $matiere;

    /**
     * @ORM\ManyToOne(targetEntity=Inscription::class, inversedBy="assiduite_app")
     */
    private $apprenant;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $presence;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getHeureCours(): ?string
    {
        return $this->heure_cours;
    }

    public function setHeureCours(string $heure_cours): self
    {
        $this->heure_cours = $heure_cours;

        return $this;
    }

    public function getMatiere(): ?Matiere
    {
        return $this->matiere;
    }

    public function setMatiere(?Matiere $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    public function getApprenant(): ?Inscription
    {
        return $this->apprenant;
    }

    public function setApprenant(?Inscription $apprenant): self
    {
        $this->apprenant = $apprenant;

        return $this;
    }

    public function getPresence(): ?string
    {
        return $this->presence;
    }

    public function setPresence(string $presence): self
    {
        $this->presence = $presence;

        return $this;
    }
}

src/Form/AssiduiteType.php
<?php

namespace App\Form;

use App\Entity\Matiere;
use App\Entity\Assiduite;
use App\Entity\Inscription;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class AssiduiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                "attr" => array (
                    "class" => "form-control",                        
                    'required'   => true,                    
                )
            ])
            ->add('heure_cours', TextType::class, [
                "attr" => array (
                    "class" => "form-control",
                    'required'   => true,
                )
            ])
            ->add('matiere', EntityType::class, [
                'placeholder' => 'Veuillez choisir',
                "attr" => array (
                    "class" => "form-control"
                 ),
                'class' => Matiere::class,
                'query_builder' => function(EntityRepository $matiere){
                    return $matiere->createQueryBuilder('m')
                            ->orderBy('m.nom_matiere', 'ASC');
                }
            ])
            ->add('apprenant', EntityType::class, [
                'placeholder' => 'Veuillez choisir',
                "attr" => array (
                    "class" => "form-control"
                 ),
                'class' => Inscription::class,
                'query_builder' => function(EntityRepository $apprenant){
                    return $apprenant->createQueryBuilder('a')
                            ->orderBy('a.nom_app', 'ASC');
                }
            ])
            ->add('presence', ChoiceType::class, [
                'placeholder' => 'Veuillez choisir',
                "attr" => array (
                    "class" => "form-control",
                    'required'   => true,
                ),
                'choices' => [
                    'Absent' => 'Absent',
                    'Present' => 'Present',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Assiduite::class,
        ]);
    }
}

src/Controller/AssiduiteController.php
<?php

namespace App\Controller;

use App\Entity\Assiduite;
use App\Form\AssiduiteType;
use App\Repository\MenuUserRepository;
use App\Repository\AssiduiteRepository;
use App\Repository\MenuVisiteurRepository;
use App\Repository\MenuApprenantRepository;
use App\Repository\MenuFormateurRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MenuAdministrateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/assiduite")
 */
class AssiduiteController extends AbstractController
{
    /**
     * @Route("/", name="assiduite_index", methods={"GET"})
     */
    public function index(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,AssiduiteRepository $assiduiteRepository): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('assiduite/index.html.twig', [
            'assiduites' => $assiduiteRepository->findAll(),
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/new", name="assiduite_new", methods={"GET","POST"})
     */
    public function new(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request): Response
    {
        $assiduite = new Assiduite();
        $form = $this->createForm(AssiduiteType::class, $assiduite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($assiduite);
            $entityManager->flush();
            $this->addFlash(
                'msg','Enregistrer avec succès!'
            );

            return $this->redirectToRoute('assiduite_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('assiduite/new.html.twig', [
            'assiduite' => $assiduite,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="assiduite_show", methods={"GET"})
     */
    public function show(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Assiduite $assiduite): Response
    {
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();
        return $this->render('assiduite/show.html.twig', [
            'assiduite' => $assiduite,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="assiduite_edit", methods={"GET","POST"})
     */
    public function edit(MenuVisiteurRepository $menuVisiteur,MenuUserRepository $menuUser,MenuFormateurRepository $menuFormateur,MenuAdministrateurRepository $menuAdministrateur,MenuApprenantRepository $menuApprenant,Request $request, Assiduite $assiduite): Response
    {
        $form = $this->createForm(AssiduiteType::class, $assiduite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash(
                'msg','Modification réussit!'
            );

            return $this->redirectToRoute('assiduite_index', [], Response::HTTP_SEE_OTHER);
        }
        $roleApprenant = 'ROLE_APPRENANT';
        $roleAdmin = 'ROLE_ADMIN';
        $roleFormateur = 'ROLE_FORMATEUR';
        $roleVisiteur = 'ROLE_VISITEUR';
        $roleUtilisateur = 'ROLE_UTILISATEUR';
        $mA = $menuApprenant->findAll();
        $mAd = $menuAdministrateur->findAll();
        $mF = $menuFormateur->findAll();
        $mU = $menuUser->findAll();
        $mV = $menuVisiteur->findAll();

        return $this->renderForm('assiduite/edit.html.twig', [
            'assiduite' => $assiduite,
            'form' => $form,
            'menuApprenant' => $mA,
            'menuAdmin' => $mAd,
            'menuFormateur' => $mF,
            'menuUser' => $mU,
            'menuVisiteur' => $mV,
            'roleApprenant' => $roleApprenant,
            'roleAdmin' => $roleAdmin,
            'roleFormateur' => $roleFormateur,
            'roleVisiteur' => $roleVisiteur,
            'roleUtilisateur' => $roleUtilisateur,
        ]);
    }

    /**
     * @Route("/{id}", name="assiduite_delete", methods={"POST"})
     */
    public function delete(Request $request, Assiduite $assiduite): Response
    {
        if ($this->isCsrfTokenValid('delete'.$assiduite->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($assiduite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('assiduite_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/assiduite/_delete_form.html.twig
<form method="post" action="{{ path('assiduite_delete', {'id': assiduite.id}) }}" onsubmit="return confirm('Etes-vous sur de supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ assiduite.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/assiduite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification assiduite{% endblock %}

{% block body %}
	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('assiduite_index') }}" class="btn btn-sm btn-neutral">Aller à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="col-xl-12 order-xl-1">
				<div class="card">
					{{ form_start(form) }}
					<div class="card-header">
						<div class="row align-items-center">
							<div class="col-8">
								<h3 class="mb-0">Modification assiduite
								</h3>
							</div>
							<div class="col-4 text-right">
								<button class="btn btn-sm btn-primary">Modifier</button>
							</div>
						</div>
					</div>
					<div class="card-body">
						<h6 class="heading-small text-muted mb-4">Information génerale</h6>
						<div class="pl-lg-4">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Date</label>
										{{ form_widget(form.date) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Heure du cours</label>
										{{ form_widget(form.heure_cours) }}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Matière</label>
										{{ form_widget(form.matiere) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Apprenant</label>
										{{ form_widget(form.apprenant) }}
									</div>
								</div>
							</div>
                            <div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Presence</label>
										{{ form_widget(form.presence) }}
									</div>
								</div>
							</div>                            
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
			{{include ("include/footer.html.twig")}}
		{% endblock %}

templates/assiduite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des assiduites
{% endblock %}
{% set active = 'assiduite'%}
{% block body %}
	{{include ("include/menu.html.twig")}}

	<div class="main-content" id="panel">

		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('assiduite_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							{# <a href="#" class="btn btn-sm btn-neutral">Filtre</a> #}
						</div>
					</div>
				</div>
				<div class="row align-items-center py-4">
					<div class="col-lg-9 col-8"></div>
					<div class="col-lg-3 col-4 text-right">
					{% for message in app.flashes('msg') %}
						<div class="alert alert-success alert-dismissible fade show" role="alert">
							<strong>{{message}}</strong>
							<button type="button" class="close" data-dismiss="alert" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
					{% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-7">
									<h3 class="mb-0">Liste des assiduites
									</h3>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table id="datatable-search">
								<thead class="thead-light">
									<tr>
										<th scope="col"><strong>Date</strong></th>
										<th scope="col"><strong>Heure du cours</strong></th>
										<th scope="col"><strong>Matière</strong></th>
										<th scope="col"><strong>Apprenant</strong></th>
										<th scope="col"><strong>Presence</strong></th>
										<th scope="col"><strong>Actions</strong></th>
									</tr>
								</thead>
								<tbody class="list">
									{% for assiduite in assiduites %}
										<tr>
											<td>{{ assiduite.date ? assiduite.date|date('Y-m-d') : '' }}</td>
											<td>{{ assiduite.heureCours }}</td>
											<td>{{ assiduite.matiere }}</td>
											<td>{{ assiduite.apprenant }}</td>
											<td>
												<span class="badge badge-dot mr-4">
													<i class="bg-success"></i>
													<span class="status">{{ assiduite.presence }}</span>
												</span>
											</td>
											<td>
												<div class="dropdown">
													<a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
														<i class="fas fa-ellipsis-v"></i>
													</a>
													<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
														<a class="dropdown-item" href="{{ path('assiduite_show', {'id': assiduite.id}) }}">Détail</a>
														<a class="dropdown-item" href="{{ path('assiduite_edit', {'id': assiduite.id}) }}">Modifier</a>
													</div>
												</div>
											</td>
										</tr>
									{% else %}
										<tr>
											<td colspan="5">Aucun enregistrement
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			{{include ("include/footer.html.twig")}}

		{% endblock %}

templates/assiduite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau assiduite{% endblock %}

{% block body %}
	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('assiduite_index') }}" class="btn btn-sm btn-neutral">Aller à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="col-xl-12 order-xl-1">
				<div class="card">
					{{ form_start(form) }}
					<div class="card-header">
						<div class="row align-items-center">
							<div class="col-8">
								<h3 class="mb-0">Nouveau assiduite
								</h3>
							</div>
							<div class="col-4 text-right">
								<button class="btn btn-sm btn-primary">Ajouter</button>
							</div>
						</div>
					</div>
					<div class="card-body">
						<h6 class="heading-small text-muted mb-4">Information génerale</h6>
						<div class="pl-lg-4">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Date</label>
										{{ form_widget(form.date) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Heure du cours</label>
										{{ form_widget(form.heure_cours) }}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Matière</label>
										{{ form_widget(form.matiere) }}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Apprenant</label>
										{{ form_widget(form.apprenant) }}
									</div>
								</div>
							</div>
                            <div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label class="form-control-label">Presence</label>
										{{ form_widget(form.presence) }}
									</div>
								</div>
							</div>                            
						</div>
					</div>
					{{ form_end(form) }}
				</div>
			</div>
			{{include ("include/footer.html.twig")}}
		{% endblock %}

templates/assiduite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du assiduite
{% endblock %}

{% block body %}

	{{include ("include/menu.html.twig")}}
	<div class="main-content" id="panel">
		{{include ("include/navbar.html.twig")}}
		<div class="header bg-primary pb-6">
			<div class="container-fluid">
				<div class="header-body">
					<div class="row align-items-center py-4">
						<div class="col-lg-6 col-7">
							<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
								<ol class="breadcrumb breadcrumb-links breadcrumb-dark">
									<li class="breadcrumb-item">
										<a href="#">
											<i class="fas fa-home"></i>
										</a>
									</li>
									<li class="breadcrumb-item">
										<a href="#">Gestion des apprenants</a>
									</li>
								</ol>
							</nav>
						</div>
						<div class="col-lg-6 col-5 text-right">
							<a href="{{ path('assiduite_new') }}" class="btn btn-sm btn-neutral">Ajout nouveau</a>
							<a href="{{ path('assiduite_index') }}" class="btn btn-sm btn-neutral">Retour à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid mt--6">
			<div class="row">
				<div class="col-xl order-xl-1">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col-8">
									<h3 class="mb-0">Détail de assiduite
									</h3>
								</div>
								<div class="col-4 text-right">
									{{ include('assiduite/_delete_form.html.twig') }}
								</div>
							</div>
						</div>
						<div class="card-body">
							<div class="pl-lg-4">
								<table class="table">
									<tbody>
										<tr>
											<th>Date</th>
											<td>{{ assiduite.date ? assiduite.date|date('Y-m-d') : ''  }}</td>
										</tr>
										<tr>
											<th>Heure du cours</th>
											<td>{{ assiduite.heureCours }}</td>
										</tr>
										<tr>
											<th>Matiere</th>
											<td>{{ assiduite.matiere }}</td>
										</tr>
										<tr>
											<th>Apprenant</th>
											<td>{{ assiduite.apprenant }}</td>
										</tr>
										<tr>
											<th>Presence</th>
											<td>
												<span class="badge badge-dot mr-4">
													<i class="bg-success"></i>
													<span class="status">{{ assiduite.presence }}</span>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{{include ("include/footer.html.twig")}}

{% endblock %}